name = "id-photo-cropper-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"
account_id = "ac84cd15621345d498951657995983aa"

[vars]
GOOGLE_CLIENT_ID = "624931143932-k6lq1k4up4nd98qb21ptfc9h7th7k07b.apps.googleusercontent.com"
REMOVE_BG_API_KEY = "BWAmXQmNFVhdbPXozJzLBisJ"

[[d1_databases]]
binding = "DB"
database_name = "id-photo-users"
database_id = "88446efb-9d64-4c8f-834f-6ffdb7c77b50"
